//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrarySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KütüphaneÖdevEntities : DbContext
    {
        public KütüphaneÖdevEntities()
            : base("name=KütüphaneÖdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlınanTablosu> AlınanTablosu { get; set; }
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<Bildirimler> Bildirimler { get; set; }
        public virtual DbSet<Tabloİade> Tabloİade { get; set; }
        public virtual DbSet<TabloKitap> TabloKitap { get; set; }
        public virtual DbSet<TabloKullanıcı> TabloKullanıcı { get; set; }
    }
}
