//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TabloKitap
    {
       
        public int ID { get; set; }
        [Required]
        public string Ad { get; set; }
        [Required]
        public int Sayfa { get; set; }
        [Required]
        public string Kategori { get; set; }
        [Required]
        public string Yazar { get; set; }
        [Required]
        public int Yıl { get; set; }
        [Required]
        public int Adet { get; set; }
    }
}
