//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TabloKullanıcı
    {
        public int ID { get; set; }

        [Required]
        public string KullanıcıAdı { get; set; }

        [Required]
        public string Şifre { get; set; }

        public int Derece { get; set; }

        public string nullableOldPassword { get; set; }

        public string nullableNewPassword { get; set; }
    }
}
